# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/wifibroadcast-rc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/wifibroadcast-rc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/wifibroadcast-rc/CMakeFiles /home/pi/wifibroadcast-rc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/wifibroadcast-rc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named joystick_ppm_converter

# Build rule for target.
joystick_ppm_converter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 joystick_ppm_converter
.PHONY : joystick_ppm_converter

# fast build rule for target.
joystick_ppm_converter/fast:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/build
.PHONY : joystick_ppm_converter/fast

joystick.o: joystick.cpp.o

.PHONY : joystick.o

# target to build an object file
joystick.cpp.o:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/joystick.cpp.o
.PHONY : joystick.cpp.o

joystick.i: joystick.cpp.i

.PHONY : joystick.i

# target to preprocess a source file
joystick.cpp.i:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/joystick.cpp.i
.PHONY : joystick.cpp.i

joystick.s: joystick.cpp.s

.PHONY : joystick.s

# target to generate assembly for a file
joystick.cpp.s:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/joystick.cpp.s
.PHONY : joystick.cpp.s

joystick_ppm.o: joystick_ppm.cpp.o

.PHONY : joystick_ppm.o

# target to build an object file
joystick_ppm.cpp.o:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/joystick_ppm.cpp.o
.PHONY : joystick_ppm.cpp.o

joystick_ppm.i: joystick_ppm.cpp.i

.PHONY : joystick_ppm.i

# target to preprocess a source file
joystick_ppm.cpp.i:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/joystick_ppm.cpp.i
.PHONY : joystick_ppm.cpp.i

joystick_ppm.s: joystick_ppm.cpp.s

.PHONY : joystick_ppm.s

# target to generate assembly for a file
joystick_ppm.cpp.s:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/joystick_ppm.cpp.s
.PHONY : joystick_ppm.cpp.s

joystick_state.o: joystick_state.cpp.o

.PHONY : joystick_state.o

# target to build an object file
joystick_state.cpp.o:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/joystick_state.cpp.o
.PHONY : joystick_state.cpp.o

joystick_state.i: joystick_state.cpp.i

.PHONY : joystick_state.i

# target to preprocess a source file
joystick_state.cpp.i:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/joystick_state.cpp.i
.PHONY : joystick_state.cpp.i

joystick_state.s: joystick_state.cpp.s

.PHONY : joystick_state.s

# target to generate assembly for a file
joystick_state.cpp.s:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/joystick_state.cpp.s
.PHONY : joystick_state.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/main.cpp.s
.PHONY : main.cpp.s

ppm_stream.o: ppm_stream.cpp.o

.PHONY : ppm_stream.o

# target to build an object file
ppm_stream.cpp.o:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/ppm_stream.cpp.o
.PHONY : ppm_stream.cpp.o

ppm_stream.i: ppm_stream.cpp.i

.PHONY : ppm_stream.i

# target to preprocess a source file
ppm_stream.cpp.i:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/ppm_stream.cpp.i
.PHONY : ppm_stream.cpp.i

ppm_stream.s: ppm_stream.cpp.s

.PHONY : ppm_stream.s

# target to generate assembly for a file
ppm_stream.cpp.s:
	$(MAKE) -f CMakeFiles/joystick_ppm_converter.dir/build.make CMakeFiles/joystick_ppm_converter.dir/ppm_stream.cpp.s
.PHONY : ppm_stream.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... joystick_ppm_converter"
	@echo "... joystick.o"
	@echo "... joystick.i"
	@echo "... joystick.s"
	@echo "... joystick_ppm.o"
	@echo "... joystick_ppm.i"
	@echo "... joystick_ppm.s"
	@echo "... joystick_state.o"
	@echo "... joystick_state.i"
	@echo "... joystick_state.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... ppm_stream.o"
	@echo "... ppm_stream.i"
	@echo "... ppm_stream.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

